Atualização nas schemas
outrowender/uno-backend pull request #10
Opened 2021-08-27 23:26 UTC by Ianesosaraiva

2021-08-27 23:36 UTC, NicolasBls commented on src/controllers/create-room-controller.ts
> +            debugger;
Dear Ane, pls remove debugger;

2021-08-27 23:37 UTC, NicolasBls commented on src/controllers/create-room-controller.ts
> +                owner: "DearAne",
vc n é a dona, querida!

2021-08-27 23:39 UTC, NicolasBls requested changes
Dear Ane,  por favor prestar mais atenção nos codigos deixado durante o teste no desenvolvimento. ;)

2021-08-27 23:40 UTC, Ianesosaraiva commented on src/controllers/create-room-controller.ts
> +                owner: "DearAne",
Disse o sujo pro mal lavado...

2021-08-28 00:17 UTC, outrowender approved these changes
Parabéns, nota zero

2021-08-28 00:22 UTC, NicolasBls reviewed
Gosto assim, mando e vc obedece!!!

2021-08-28 00:23 UTC, outrowender approved these changes

2021-08-28 00:24 UTC, merged